format = """\
[╭╴](fg:arrow)\
$username\
$directory\
$time\
(\
    $git_branch\
    $git_status\
)\
(\
    $python\
    $conda\
    $nodejs\
)\
$status\
$cmd_duration
[╰─](fg:arrow)$character\
"""

add_newline = true

palette = "normal"

[palettes.normal]
arrow = "#353535"
os = "#3271AE"
os_admin = "#7C191E"
directory = "#DD6B7B"
time = "#4C8045"
node = "green"
git = "#B02B10"
git_status = "#8B1D2C"
python = "#3776AB"
conda = "#3EB049"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "#1E2732"
error = "#7C191E"
text_color = "#EDF2F4"
text_light = "#EDF2F4"


[username]
style_user = 'os'
style_root = 'os_admin'
format = '[]($style)[󰄛 Asher](bg:$style fg:text_color)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:arrow)"

[status]
disabled = false
format = ' [](fg:error)[$symbol$status](bg:error fg:text_color)[](fg:error)'
symbol = "✘ "

[directory]
format = " [](fg:directory)[  $path ]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[time]
disabled = false
format = " [](fg:time)[ $time]($style)[](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"

[cmd_duration]
format = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style = "fg:text_light bg:duration"
min_time = 500

[git_branch]
format = " [](fg:git)[$symbol$branch](fg:text_light bg:git)[](fg:git)"
symbol = " "

[git_status]
format = '( [](fg:git_status)[ $all_status$ahead_behind ]($style)[](fg:git_status))'
style = "fg:text_light bg:git_status"

[docker_context]
disabled=true
symbol = " "

[package]
disabled=true

[java]
format = " [](fg:java)[$symbol$version](bg:java fg:text_color)[](fg:java)"
version_format = "${raw}"
symbol = " "
disabled = true

[nodejs]
format = " [](fg:node)[$symbol$version]($style)[](fg:node)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled=false

[rust]
format = " [](fg:rust)[$symbol$version](bg:rust fg:text_color)[](fg:rust)"
symbol = " "
version_format = "${raw}"
disabled=true

[python]
disabled=false
format = ' [](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](fg:python)'
symbol = " "
version_format = "${raw}"
style = "fg:text_light bg:python"

[conda]
format = " [](fg:conda)[$symbol$environment]($style)[](fg:conda)"
style = "bg:conda fg:text_color"
ignore_base = false
disabled=false
symbol = " "

[c]
format = " [](fg:clang)[$symbol($version(-$name) )](bg:clang fg:text_color)[](fg:clang)"
symbol = " "
version_format = "${raw}"
disabled=true
